Algoritmo "media de quadro notas bimestrais"

Var
 nota1, nota2, nota3, nota4: inteiro
 media: real

Inicio
  escreval ("Escreva a primeira nota")
  Leia (nota1)
   escreval ("Escreva a segunda nota")
  Leia (nota2)
   escreval ("Escreva a terceira nota")
  Leia (nota3)
   escreval ("Escreva a quarta nota")
  Leia (nota4)
  media := (nota1+nota2+nota3+nota4)\4

  escreva ("A media é: ", media)
Fimalgoritmo