Algoritmo "Vogal ou consoante"

Var
letra: caractere

Inicio
 Escreval ("Digite uma letra aleatoria")
 leia(letra)
 se (letra = "a") ou (letra = "e") ou (letra = "i") ou  (letra = "o") ou (letra = "u") ou  (letra = "A") ou (letra = "E") ou (letra = "I") ou  (letra = "O") ou (letra = "U") entao
 escreval(letra, " é uma vogal")
 senao
 escreval (letra,  " é uma consoante")
   fimse
Fimalgoritmo
